[package]
name = "multi-protocol-file-manager"
version = "0.1.0"
edition = "2021"
description = "A multi-protocol file manager built on OpenDAL"
authors = ["MultiProtocolFileManager <info@example.com>"]
license = "MIT"

[dependencies]
opendal = { version = "0.40.0", features = ["services-s3"] }
tokio = { version = "1.32", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
dirs = "5.0"
chrono = "0.4"
indicatif = "0.17"
prettytable-rs = "0.10"
uuid = { version = "1.5", features = ["v4"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true