# Windows 7 兼容性配置
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=/SUBSYSTEM:WINDOWS,6.01"  # Windows 7 兼容性
]

# Windows 特定的环境变量
[target.x86_64-pc-windows-msvc.env]
WINVER = "0x0601"
_WIN32_WINNT = "0x0601"