name: Tests

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'src/**'
      - 'ui/src/**'
      - 'Cargo.toml'
      - 'ui/package.json'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'src/**'
      - 'ui/src/**'
      - 'Cargo.toml'
      - 'ui/package.json'

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-tests:
    name: Rust Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Basic lib
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build project
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --lib --verbose

      - name: Run integration tests
        run: cargo test --test '*' --verbose

      - name: Run documentation tests
        run: cargo test --doc --verbose

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install && cd ui && pnpm install

      - name: TypeScript type checking
        run: cd ui && pnpm run type-check

      - name: Build frontend
        run: cd ui && pnpm run build

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(fromJson('["master", "develop"]'), github.ref_name)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Basic lib
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: cargo audit

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install && cd ui && pnpm install

      - name: Run npm audit
        run: cd ui && pnpm audit || echo "Audit completed with warnings"
